language: go
osx_image: xcode10.2
sudo: true

go:
  - 1.11.x
  - master

os:
  - linux
  - osx

env:
  - GO111MODULE=on

cache:
  directories:
    - node_modules

script:
  - bash build.sh all 99.99 clear
